### ISSUE TITLE
Adding hidden lat-long fields?

### ISSUE THREAD

**Issue by andrewblossom** [oomphinc/gravity-forms-google-places#6]
While having the base formatted location is nice, it'd be great to have the lat-long fields auto-populated by the Google Places API (in hidden fields) submitted as well. Any chance that feature could be added?

**Comment by balbuf** [comment]
Hi @andrewblossom ! Unfortunately we haven't had enough time to draft a proper readme for this plugin, but I take it you came across this functionality already? Let me know if you have any further questions.

**Comment by andrewblossom** [comment]
I've been trying to modify the plugin to include the hidden lat-long fields - I have them populating but not actually submitting to gravity forms. Is this functionality actually built-in and I've missed it?

**Comment by andrewblossom** [comment]
I JUST came across the functionality. Can you give me a few pointers on what I should put in the 'field id' and 'component' fields on the hidden field so I don't have to trial-and-error my way through it?

**Comment by balbuf** [comment]
Hi @andrewblossom ! The "Field ID" field should be the gravity forms field ID for the Google Places form element, e.g. this would be ID 1:
![screen shot 2016-08-04 at 6 14 39 pm](https://cloud.githubusercontent.com/assets/3887845/17420195/66d30f8c-5a6f-11e6-9271-9355b1283a80.png)

and the "component" field is the piece of information you want to collect from the places API. The available options can be found under the "Address and Places Component Types" section at https://ubilabs.github.io/geocomplete/

LMK if you have anymore questions!

**Comment by balbuf** [comment]
Hi @andrewblossom  - was that the functionality that you were looking for? Feel free to close the issue if that works for you. Thanks!

**Comment by andrewblossom** [comment]
Yes, it was. Thank you!
